version: "3"

networks:
  jenkins-net:

services:
  jenkins:
    build: .
    container_name: jenkins
#    user: root
    ports:
      - "8088:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Duser.timezone=Asia/Karachi
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
#    restart: unless-stopped
    networks:
      jenkins-net:

volumes:
  jenkins_home:
